modLoader="lowcodefml"
loaderVersion="[1,)"
license="Stardust Labs License"
issueTrackerURL="https://github.com/Stardust-Labs-MC/Structory/issues"

[[mods]]
    modId="structory"
    version="1.3.5"
    displayName="Structory"
    displayURL="https://www.stardustlabs.net/"
    logoFile="pack.png"
    authors="Stardust Labs"
    credits="Botany: Owner. Starmute: Developer. catter1: Maintainer."
    description="An atmospheric structure mod with detailed themes, varied builds, and light lore. Occasionally recieves seasonal updates and add-ons."

[[dependencies.structory]]
    modId="neoforge"
    mandatory=false
    versionRange="[20.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.structory]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
